# Generated by Django 3.2.3 on 2022-05-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('descripcionProducto', models.CharField(max_length=200, verbose_name='Descripción del producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombreUsuario', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre de usuario')),
                ('contrasenaUsuario', models.CharField(max_length=15, verbose_name='Contraseña de usuario')),
            ],
        ),
    ]
