# Generated by Django 3.2.3 on 2022-05-04 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRemedio',
            fields=[
                ('idCategoriaRemedio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la categoria del remedio')),
                ('nombreCategoriaRemedio', models.CharField(max_length=50, verbose_name='Nombre de la categoría del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('idRemedio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del remedio')),
                ('nombreRemedio', models.CharField(max_length=50, verbose_name='Nombre del remedio')),
                ('descripcionRemedio', models.CharField(max_length=120, verbose_name='Descripción del remedio')),
                ('categoriaRemedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaremedio')),
            ],
        ),
    ]
