# Generated by Django 3.2.3 on 2022-05-05 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_remedio_descripcionremedio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaRemedio',
            fields=[
                ('idMarcaRemedio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Marca del remedio')),
                ('nombreMarcaRemedio', models.CharField(max_length=50, verbose_name='Nombre de la marca del remedio')),
            ],
        ),
        migrations.AddField(
            model_name='remedio',
            name='stockRemedio',
            field=models.IntegerField(default=0, verbose_name='Stock del remedio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedio',
            name='marcaRemedio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.marcaremedio'),
            preserve_default=False,
        ),
    ]
