# Generated by Django 4.0.4 on 2022-05-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remedio_cantidadremedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='medc'),
        ),
    ]
