# Generated by Django 4.0.4 on 2022-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remedio_imagenremedio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='remedio',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
