# Generated by Django 4.0.4 on 2022-05-12 05:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_remedio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedio',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
