# Generated by Django 4.0.4 on 2022-05-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_remedio_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedio',
            name='slug',
        ),
    ]
